// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7RIhWKyiJZzKuqzIAqQWqSMsLM9TG_4',
    appId: '1:172789913782:web:47429a5f6ed85e259cee17',
    messagingSenderId: '172789913782',
    projectId: 'librico-cb904',
    authDomain: 'librico-cb904.firebaseapp.com',
    storageBucket: 'librico-cb904.firebasestorage.app',
    measurementId: 'G-5XFSENT9H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP5QdXxuI6Uy0rfG0_nIItfdFSdJKPLK8',
    appId: '1:172789913782:android:329de57b91af035b9cee17',
    messagingSenderId: '172789913782',
    projectId: 'librico-cb904',
    storageBucket: 'librico-cb904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqE9MGJCICadTUGuWFG5wCJnvHCRfD1Sg',
    appId: '1:172789913782:ios:16e1fdcc2d2bd3429cee17',
    messagingSenderId: '172789913782',
    projectId: 'librico-cb904',
    storageBucket: 'librico-cb904.firebasestorage.app',
    iosBundleId: 'com.example.librico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqE9MGJCICadTUGuWFG5wCJnvHCRfD1Sg',
    appId: '1:172789913782:ios:16e1fdcc2d2bd3429cee17',
    messagingSenderId: '172789913782',
    projectId: 'librico-cb904',
    storageBucket: 'librico-cb904.firebasestorage.app',
    iosBundleId: 'com.example.librico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp7RIhWKyiJZzKuqzIAqQWqSMsLM9TG_4',
    appId: '1:172789913782:web:9190c90cded541c49cee17',
    messagingSenderId: '172789913782',
    projectId: 'librico-cb904',
    authDomain: 'librico-cb904.firebaseapp.com',
    storageBucket: 'librico-cb904.firebasestorage.app',
    measurementId: 'G-5RLN1M0NG6',
  );
}
